// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using internshipProject1.Infrastructure.Context;

#nullable disable

namespace internshipProject1.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("internshipproject1.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerId1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerId1")
                        .IsUnique();

                    b.ToTable("Card");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.CardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("CardId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VehicleType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("CardTransaction");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentMenuId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Dashboard",
                            Url = "/dashboard"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Users",
                            Url = "/users"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Routes",
                            Url = "/routes"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Stops",
                            Url = "/stops"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Trips",
                            Url = "/trips"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Cards",
                            Url = "/cards"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Customers",
                            Url = "/customers"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Settings",
                            Url = "/settings"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Role Management",
                            Url = "/role-management"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Card Transactions",
                            Url = "/card-transactions"
                        });
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "God Mode",
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Admin - Yönetici",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "End User - Yolcu",
                            Name = "Passenger"
                        });
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.RoleMenuPermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("RoleMenuPermission");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            MenuId = 1,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 2,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 3,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 4,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 5,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 6,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 7,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 8,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 9,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 1,
                            MenuId = 10,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 1,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 2,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 3,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 4,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 5,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 6,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 7,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 8,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 9,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = false
                        },
                        new
                        {
                            RoleId = 2,
                            MenuId = 10,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 1,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = false,
                            CanUpdate = false
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 2,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = false,
                            CanUpdate = false
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 3,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = false,
                            CanUpdate = false
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 4,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = false,
                            CanUpdate = false
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 5,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = false,
                            CanUpdate = false
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 6,
                            CanCreate = true,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 7,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = false,
                            CanUpdate = false
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 8,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 9,
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true
                        },
                        new
                        {
                            RoleId = 3,
                            MenuId = 10,
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = false
                        });
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.RouteStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<int>("StopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StopId");

                    b.HasIndex("RouteId", "Order")
                        .IsUnique();

                    b.HasIndex("RouteId", "StopId")
                        .IsUnique();

                    b.ToTable("RouteStop");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.RouteToCreate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EndLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stop");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("passwordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.UserRoles", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Card", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.Customer", "Customer")
                        .WithMany("CardList")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("internshipproject1.Domain.Entities.Customer", null)
                        .WithOne("Card")
                        .HasForeignKey("internshipproject1.Domain.Entities.Card", "CustomerId1");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.CardTransaction", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.Card", "Card")
                        .WithMany("CardTransactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Customer", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("internshipproject1.Domain.Entities.Customer", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Menu", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.Menu", "ParentMenu")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentMenuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentMenu");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.RoleMenuPermission", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.Menu", "Menu")
                        .WithMany("RoleMenuPermissions")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("internshipproject1.Domain.Entities.Role", "Role")
                        .WithMany("RoleMenuPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.RouteToCreate", "Route")
                        .WithMany("RouteStops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("internshipproject1.Domain.Entities.Stop", "Stop")
                        .WithMany("RouteStops")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Stop");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.RouteToCreate", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedRoutes")
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Trip", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.RouteToCreate", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.UserRoles", b =>
                {
                    b.HasOne("internshipproject1.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("internshipproject1.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Card", b =>
                {
                    b.Navigation("CardTransactions");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Card")
                        .IsRequired();

                    b.Navigation("CardList");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Menu", b =>
                {
                    b.Navigation("RoleMenuPermissions");

                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Role", b =>
                {
                    b.Navigation("RoleMenuPermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.RouteToCreate", b =>
                {
                    b.Navigation("RouteStops");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.Stop", b =>
                {
                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("internshipproject1.Domain.Entities.User", b =>
                {
                    b.Navigation("CreatedRoutes");

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
